use crate::map::tiles::TILE_BULL_BIT;
use crate::map::tiles_type::TileType;

/// Default radius of an island.
pub const ISLAND_RADIUS: i16 = 18;

pub const SMOOTH_TILES_DX: [i32; 4] = [-1, 0, 1, 0];
pub const SMOOTH_TILES_DY: [i32; 4] = [0, 1, 0, -1];
pub const SMOOTH_RIVER_EDGES_TABLE: [u16; 16] = [
    13 | TILE_BULL_BIT,
    13 | TILE_BULL_BIT,
    17 | TILE_BULL_BIT,
    15 | TILE_BULL_BIT,
    5 | TILE_BULL_BIT,
    TileType::River as u16,
    19 | TILE_BULL_BIT,
    17 | TILE_BULL_BIT,
    9 | TILE_BULL_BIT,
    11 | TILE_BULL_BIT,
    TileType::River as u16,
    13 | TILE_BULL_BIT,
    7 | TILE_BULL_BIT,
    9 | TILE_BULL_BIT,
    5 | TILE_BULL_BIT,
    TileType::River as u16,
];
pub const SMOOTH_FOREST_EDGES_TABLE: [u16; 16] = [
    TileType::Dirt as u16,
    TileType::Dirt as u16,
    TileType::Dirt as u16,
    34,
    TileType::Dirt as u16,
    TileType::Dirt as u16,
    36,
    35,
    TileType::Dirt as u16,
    32,
    TileType::Dirt as u16,
    33,
    30,
    31,
    29,
    TileType::Woods as u16,
];

pub const BLOB_RIVER_SMALL: [[TileType; 6]; 6] = [
    [
        TileType::Dirt,
        TileType::Dirt,
        TileType::RiverEdge,
        TileType::RiverEdge,
        TileType::Dirt,
        TileType::Dirt,
    ],
    [
        TileType::Dirt,
        TileType::RiverEdge,
        TileType::River,
        TileType::River,
        TileType::RiverEdge,
        TileType::Dirt,
    ],
    [
        TileType::RiverEdge,
        TileType::River,
        TileType::River,
        TileType::River,
        TileType::River,
        TileType::RiverEdge,
    ],
    [
        TileType::RiverEdge,
        TileType::River,
        TileType::River,
        TileType::River,
        TileType::River,
        TileType::RiverEdge,
    ],
    [
        TileType::Dirt,
        TileType::RiverEdge,
        TileType::River,
        TileType::River,
        TileType::RiverEdge,
        TileType::Dirt,
    ],
    [
        TileType::Dirt,
        TileType::Dirt,
        TileType::RiverEdge,
        TileType::RiverEdge,
        TileType::Dirt,
        TileType::Dirt,
    ],
];

pub const BLOB_RIVER_BIG: [[TileType; 9]; 9] = [
    [
        TileType::Dirt,
        TileType::Dirt,
        TileType::Dirt,
        TileType::RiverEdge,
        TileType::RiverEdge,
        TileType::RiverEdge,
        TileType::Dirt,
        TileType::Dirt,
        TileType::Dirt,
    ],
    [
        TileType::Dirt,
        TileType::Dirt,
        TileType::RiverEdge,
        TileType::River,
        TileType::River,
        TileType::River,
        TileType::RiverEdge,
        TileType::Dirt,
        TileType::Dirt,
    ],
    [
        TileType::Dirt,
        TileType::RiverEdge,
        TileType::River,
        TileType::River,
        TileType::River,
        TileType::River,
        TileType::River,
        TileType::RiverEdge,
        TileType::Dirt,
    ],
    [
        TileType::RiverEdge,
        TileType::River,
        TileType::River,
        TileType::River,
        TileType::River,
        TileType::River,
        TileType::River,
        TileType::River,
        TileType::RiverEdge,
    ],
    [
        TileType::RiverEdge,
        TileType::River,
        TileType::River,
        TileType::River,
        TileType::Channel,
        TileType::River,
        TileType::River,
        TileType::River,
        TileType::RiverEdge,
    ],
    [
        TileType::RiverEdge,
        TileType::River,
        TileType::River,
        TileType::River,
        TileType::River,
        TileType::River,
        TileType::River,
        TileType::River,
        TileType::RiverEdge,
    ],
    [
        TileType::Dirt,
        TileType::RiverEdge,
        TileType::River,
        TileType::River,
        TileType::River,
        TileType::River,
        TileType::River,
        TileType::RiverEdge,
        TileType::Dirt,
    ],
    [
        TileType::Dirt,
        TileType::Dirt,
        TileType::RiverEdge,
        TileType::River,
        TileType::River,
        TileType::River,
        TileType::RiverEdge,
        TileType::Dirt,
        TileType::Dirt,
    ],
    [
        TileType::Dirt,
        TileType::Dirt,
        TileType::Dirt,
        TileType::RiverEdge,
        TileType::RiverEdge,
        TileType::RiverEdge,
        TileType::Dirt,
        TileType::Dirt,
        TileType::Dirt,
    ],
];
